name: Telegram Message on Pull Request

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message on Pull Request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Pull Request Merged!
            
            ${{ github.event.pull_request.title }} was merged into main branch by ${{ github.actor }}
            
            Pull Request URL: ${{ github.event.pull_request.html_url }}
